namespace PicoCfg.Gen.Generator;

using System;
using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

public sealed partial class PicoCfgBindGenerator
{
    private static string Render(IReadOnlyList<TargetModel> targets)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("namespace PicoCfg;");
        sb.AppendLine();
        sb.AppendLine("[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]");
        sb.AppendLine("internal static class PicoCfgBindGeneratedRegistrations");
        sb.AppendLine("{");
        sb.AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializerAttribute]");
        sb.AppendLine("    internal static void Initialize()");
        sb.AppendLine("    {");

        for (var i = 0; i < targets.Count; i++)
        {
            var target = targets[i];
            var typeName = target.TargetType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var bindDelegateType = "global::System.Func<global::PicoCfg.Abs.ICfg, string?, " + typeName + ">";
            var tryBindDelegateType = "global::PicoCfg.PicoCfgGeneratedTryBindDelegate<" + typeName + ">";
            var bindIntoDelegateType = "global::PicoCfg.PicoCfgGeneratedBindIntoDelegate<" + typeName + ">";
            var hasCtor = target.HasPublicParameterlessConstructor ? "(" + bindDelegateType + ")Bind_" + i : "null";
            var hasTryBind = target.HasPublicParameterlessConstructor ? "(" + tryBindDelegateType + ")TryBind_" + i : "null";

            sb.Append("        global::PicoCfg.CfgBindRuntime.Register<").Append(typeName).AppendLine(">(");
            sb.AppendLine("            contractVersion: global::PicoCfg.CfgBindRuntime.ContractVersion,");
            sb.Append("            bind: ").Append(hasCtor).AppendLine(",");
            sb.Append("            tryBind: ").Append(hasTryBind).AppendLine(",");
            sb.Append("            bindInto: (").Append(bindIntoDelegateType).Append(")BindInto_").Append(i).AppendLine(");");
            sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine();

        for (var i = 0; i < targets.Count; i++)
            AppendTargetMethods(sb, targets[i], i);

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void AppendTargetMethods(StringBuilder sb, TargetModel target, int index)
    {
        var typeName = target.TargetType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        if (target.HasPublicParameterlessConstructor)
        {
            sb.Append("    private static ").Append(typeName).Append(" Bind_").Append(index).AppendLine("(global::PicoCfg.Abs.ICfg cfg, string? section)");
            sb.AppendLine("    {");
            sb.Append("        var instance = new ").Append(typeName).AppendLine("();");
            sb.Append("        BindInto_").Append(index).AppendLine("(cfg, section, instance);");
            sb.AppendLine("        return instance;");
            sb.AppendLine("    }");
            sb.AppendLine();

            sb.Append("    private static bool TryBind_").Append(index).Append("(global::PicoCfg.Abs.ICfg cfg, string? section, out ").Append(typeName).AppendLine(" value)");
            sb.AppendLine("    {");
            sb.Append("        var instance = new ").Append(typeName).AppendLine("();");
            sb.Append("        if (!TryBindInto_").Append(index).AppendLine("(cfg, section, instance))");
            sb.AppendLine("        {");
            sb.AppendLine("            value = default!;");
            sb.AppendLine("            return false;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        value = instance;");
            sb.AppendLine("        return true;");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.Append("    private static void BindInto_").Append(index).Append("(global::PicoCfg.Abs.ICfg cfg, string? section, ").Append(typeName).AppendLine(" instance)");
        sb.AppendLine("    {");
        foreach (var property in target.Properties)
            AppendBindProperty(sb, target, property, throwOnFailure: true);
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.Append("    private static bool TryBindInto_").Append(index).Append("(global::PicoCfg.Abs.ICfg cfg, string? section, ").Append(typeName).AppendLine(" instance)");
        sb.AppendLine("    {");
        sb.AppendLine("        var any = false;");
        foreach (var property in target.Properties)
            AppendBindProperty(sb, target, property, throwOnFailure: false);
        sb.AppendLine("        return any;");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void AppendBindProperty(StringBuilder sb, TargetModel target, PropertyModel property, bool throwOnFailure)
    {
        var propertyPathLiteral = SymbolDisplay.FormatLiteral(property.Name, true);
        var targetDisplay = SymbolDisplay.FormatLiteral(property.Type.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat), true);
        var memberDisplay = SymbolDisplay.FormatLiteral(target.TargetType.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat) + "." + property.Name, true);
        var rawName = "__raw_" + property.Name;
        var pathName = "__path_" + property.Name;
        var valueName = "__value_" + property.Name;

        sb.Append("        var ").Append(pathName).Append(" = global::PicoCfg.CfgBindRuntime.CombinePath(section, ").Append(propertyPathLiteral).AppendLine(");");
        sb.Append("        if (cfg.TryGetValue(").Append(pathName).Append(", out var ").Append(rawName).AppendLine("))");
        sb.AppendLine("        {");
        if (!throwOnFailure)
            sb.AppendLine("            any = true;");

        if (property.ScalarKind == ScalarKind.String)
        {
            sb.Append("            instance.").Append(property.Name).Append(" = ").Append(rawName).AppendLine(";");
        }
        else if (property.IsNullable)
        {
            sb.Append("            if (string.IsNullOrEmpty(").Append(rawName).AppendLine("))");
            sb.AppendLine("            {");
            sb.Append("                instance.").Append(property.Name).AppendLine(" = null;");
            sb.AppendLine("            }");
            sb.AppendLine("            else");
            sb.AppendLine("            {");
            AppendParseBlock(sb, property, rawName, valueName, pathName, targetDisplay, memberDisplay, throwOnFailure, indent: "                ");
            sb.Append("                instance.").Append(property.Name).Append(" = ").Append(valueName).AppendLine(";");
            sb.AppendLine("            }");
        }
        else
        {
            AppendParseBlock(sb, property, rawName, valueName, pathName, targetDisplay, memberDisplay, throwOnFailure, indent: "            ");
            sb.Append("            instance.").Append(property.Name).Append(" = ").Append(valueName).AppendLine(";");
        }

        sb.AppendLine("        }");
    }

    private static void AppendParseBlock(
        StringBuilder sb,
        PropertyModel property,
        string rawName,
        string valueName,
        string pathName,
        string targetDisplay,
        string memberDisplay,
        bool throwOnFailure,
        string indent
    )
    {
        var targetTypeName = property.UnderlyingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var parseCall = GetParseCall(property.ScalarKind, rawName, valueName, targetTypeName);

        sb.Append(indent).Append("if (!").Append(parseCall).AppendLine(")");
        sb.Append(indent).AppendLine("{");
        if (throwOnFailure)
        {
            sb.Append(indent)
                .Append("    throw global::PicoCfg.CfgBindRuntime.CreateConversionException(")
                .Append(pathName)
                .Append(", ")
                .Append(targetDisplay)
                .Append(", ")
                .Append(memberDisplay)
                .AppendLine(");");
        }
        else
        {
            sb.Append(indent).AppendLine("    return false;");
        }

        sb.Append(indent).AppendLine("}");
    }

    private static string GetParseCall(ScalarKind scalarKind, string rawName, string valueName, string targetTypeName)
        => scalarKind switch
        {
            ScalarKind.Boolean => $"global::PicoCfg.CfgBindRuntime.TryParseBoolean({rawName}, out var {valueName})",
            ScalarKind.Byte => $"global::PicoCfg.CfgBindRuntime.TryParseByte({rawName}, out var {valueName})",
            ScalarKind.SByte => $"global::PicoCfg.CfgBindRuntime.TryParseSByte({rawName}, out var {valueName})",
            ScalarKind.Int16 => $"global::PicoCfg.CfgBindRuntime.TryParseInt16({rawName}, out var {valueName})",
            ScalarKind.UInt16 => $"global::PicoCfg.CfgBindRuntime.TryParseUInt16({rawName}, out var {valueName})",
            ScalarKind.Int32 => $"global::PicoCfg.CfgBindRuntime.TryParseInt32({rawName}, out var {valueName})",
            ScalarKind.UInt32 => $"global::PicoCfg.CfgBindRuntime.TryParseUInt32({rawName}, out var {valueName})",
            ScalarKind.Int64 => $"global::PicoCfg.CfgBindRuntime.TryParseInt64({rawName}, out var {valueName})",
            ScalarKind.UInt64 => $"global::PicoCfg.CfgBindRuntime.TryParseUInt64({rawName}, out var {valueName})",
            ScalarKind.Single => $"global::PicoCfg.CfgBindRuntime.TryParseSingle({rawName}, out var {valueName})",
            ScalarKind.Double => $"global::PicoCfg.CfgBindRuntime.TryParseDouble({rawName}, out var {valueName})",
            ScalarKind.Decimal => $"global::PicoCfg.CfgBindRuntime.TryParseDecimal({rawName}, out var {valueName})",
            ScalarKind.Guid => $"global::PicoCfg.CfgBindRuntime.TryParseGuid({rawName}, out var {valueName})",
            ScalarKind.Enum => $"global::PicoCfg.CfgBindRuntime.TryParseEnum<{targetTypeName}>({rawName}, out var {valueName})",
            _ => throw new InvalidOperationException($"Unexpected scalar kind '{scalarKind}'."),
        };
}
